plugins {
    id 'java'
    id("io.github.alexpercont.xjc-plugin") version "1.1"
    id "de.undercouch.download" version "5.6.0"
}

group 'no.unit.nva'

dependencies {
    implementation group: 'jakarta.xml.bind', name: 'jakarta.xml.bind-api', version: '4.0.2'
    runtimeOnly group: 'org.glassfish.jaxb', name: 'jaxb-runtime', version: '4.0.5'
}

ext.SCHEMA_VERSION = '4.5'
ext.SCHEMA_DIR = file(layout.buildDirectory.asFile.get().toURI().toString() + '/tmp/schema')
ext.METADATA_XSD = 'metadata.xsd'
ext.DID_DOWNLOAD = new HashMap<String, Boolean>()

tasks.register('fetchSchema') {
    doLast {
        getUris().forEach {
            downloadFile(it.toString())
        }
        if (DID_DOWNLOAD.any { it.value == false }) {
            System.out.println("WARN: Some XSD files were cached from a previous run, to avoid this, run ./gradlew clean")
        }
    }
}

private List<String> getUris() {

    def source = downloadFile(METADATA_XSD)

    def xml = new groovy.xml.XmlSlurper().parseText(source.getText())

    return xml.'**'.findAll {
        it.name() == 'include' || it.name() == 'import'
    }.collect {
        it.@'schemaLocation'
    }
}

private File downloadFile(String path) {
    def uri = "https://schema.datacite.org/meta/kernel-${SCHEMA_VERSION}/${path}"
    def file = file(SCHEMA_DIR.toURI().toString() + '/' + path)

    if (!file.exists()) {
        def destination = path.contains("/") ? file.parentFile : SCHEMA_DIR
        destination.mkdirs()
        download.run {
            src uri
            dest destination
        }
        DID_DOWNLOAD.put(path, true)
    } else {
        DID_DOWNLOAD.put(path, false)
    }
    return file;
}

jar {
    from "${layout.buildDirectory}/classes/java/main"
}

tasks.named('sourcesJar') {
    dependsOn('xjc')
}


xjc {
    schema = [SCHEMA_DIR.toURI().toString() + '/' + METADATA_XSD]
}

tasks.named('xjc') {
    dependsOn('fetchSchema')
}

tasks.named('compileJava') {
    dependsOn('xjc')
}